### PR TITLE
Reorganize for dotnet CLI and restore most tests

### PR DESCRIPTION
**Pull request by samiamlabs**
Moved around a bunch of stuff to enable running tests in terminal using `dotnet test` without having to build with colcon. Watching tests like this seem better to me compared to going through monodevelop and using the mono C# compiler for development when colcon builds with dotnet. Moved the test code to a separate package as well because that seemed to be the recommended approach according to Microsofts docs.

I also added back most of the old tests. Everything except publisher initialization in NativeMethods and a strange occasional error in SubscriptionQosSensorDataDepth seems to be passing after some minor fixes.

Moving on to Azure now. Not sure if I will "cheat" to start with and use the development approach of running the test that bypasses colcon or add proper commands to cmake for building and running tests through colcon.

The developement testing approach can stop working if workspace layout changes (It uses relative paths to find the std_msgs and tests_msgs assemblies). Which is not great....

### CODE REVIEW

**Comment by adamdbrw** [comment]
Hey, this is great and much needed, thank you for the work! 
I understand it is still WIP status? I would like to run the tests on my machine, so let me know when I can (and how to).

**Comment by samiamlabs** [comment]
The CI is not working yet, but it should work in your local machine as is :)

**Comment by adamdbrw** [comment]
Great :) Let me know when you are ready to merge

**Comment by samiamlabs** [comment]
I have a circleci/docker based pipeline that builds, runs tests and pushes and the resulting image to Docker Hub on my fork now. Added a badge to the readme here: https://github.com/samiamlabs/ros2_dotnet

I gave up on Azure for the Windows builds for now (I suspect there are a bunch of settings outside the config files in the repo that need to be correct).

I think the setup for the CI builds for appveyor on Windows works but that the repo does not build on Windows at the moment. Will investigate later when I need to use Windows. Removed the CI for now.

I thought it would be nice to build both Linux and Windows on appveyor, but they have some strange python version selection stuff in their ubuntu images that messes with dependencies for colcon. Was not able to get it to build because of that.

Will need to configure a new circleci project for your fork. Only my fork shows up when I log in to circleci now.

Perhaps it would be better if I work directly on branches in your fork and submit pull requests from there instead of from my own fork?

**Comment by adamdbrw** [comment]
Merged both pull request (none is breaking).
We can work on feature branches.

**Pull request merged**
